### PR TITLE
various updates

### PR DESCRIPTION
**Pull request by notspiff**
hi,

various updates sent to my repo
- fix osx build (memphiz)
- update fractalland.frag (kib)

also i moved the presets into a struct utilizing c++11 initializer lists. makes it easier to change infos..

### CODE REVIEW

**Comment by topfs2** [comment]
Nice, ideally my plan was to update and unify rendering so we didn't need this much ifdefs. But nice with gles support anyways!

**Comment by notspiff** [comment]
sure but it is easier to abstract with two implementations at hand :)
19. mai 2015 5.20 p.m. skrev "Tobias Arrskog" notifications@github.com:

**Comment by topfs2** [comment]
Agreed! Love the help on it!
Den 19 maj 2015 5:21 em skrev "Arne Morten Kvarving" <
notifications@github.com>:

**Comment by notspiff** [comment]
Hrm i see i naughtied up a squash. Gles work was done by popcornmix.

**Pull request merged**
