### PR TITLE
add changelog + bump version

### PR DESCRIPTION
**Pull request by un1versal**
This could be helpful for packaging and distribution since new changes/additions.

Reflects changes for all commits except for #2 and #5 and accounts for #3 and #6

@wsnipex #2 will need to be bumped accordingly and if that's is merged before this PR ill add debian packing to changelog if required.

### CODE REVIEW

**Comment by topfs2** [comment]
I'm somewhat confused :) But I suspect #2 needs to go in first and you fix this up after no?

**Comment by un1versal** [comment]
#2 needs to be fixed up since its stuck at version 0.0.1

**Comment by topfs2** [comment]
Well versioning is fine IMO. Its not released yet :)

My thinking was to merge in all the stuff in the PRs then bump to 0.0.2. But perhaps that messes things up with the zip floating around by @popcornmix

**Comment by un1versal** [comment]
Versions isnt the important thing imo (per say) I just wanted to add a changelog that accounts for the things added/fixed thus far so its visible in kodi

wsnipex already ships it packaged on ppa though ;) and that will require bumps as things are added/fixed.

So let me know what version you want me to add.

To upgrade over existing you need to bump versions, new installs dont matter, released or not some people already packaging it. :)

**Edit**

ive bumped it to 0.0.2 and conglomerated the changes in changelog into 0.0.2

**Comment by popcornmix** [comment]
Actually how should the GLES2 and desktop GL versions of addons coexist?
While my tree can be built for either, it is a compile time switch, so any binary in a repo will only support GLES2 or desktop GL.

I've confirmed my repo version supports some non-pi platfoms (e.g. Wetek), but it's not going to work on desktop GL.

It seems you want something like:
`<platform>linux</platform>`
to distinguish GLES2 and desktop GL, but I'm not sure if that exists.

**Comment by topfs2** [comment]
@popcornmix I think Kodi needs to either provide an abstracted rendering API we can use (which was partly my idea with dawn) or we need to have more than one .so or addon with something along the lines of `<rendering>gl|gles|dx</rendering>`

**Comment by un1versal** [comment]
ping #2 was merged this was adjusted accordingly, would you be able to review the two other PR's and then this. I thought it be nice to push this addon to xbmc/repo-binary-addons https://github.com/xbmc/repo-binary-addons/pull/12 

its been working fine here with exception of the visualizers suggested for removal in https://github.com/topfs2/visualization.shadertoy/pull/8

**Comment by un1versal** [comment]
all upstream

**Pull request closed without merging**
